### ISSUE TITLE
can't answer

### ISSUE THREAD

**Issue by hdcola** [scmanjarrez/Edge-GPT-Telegram-Bot#12]
edgebot_1  | Traceback (most recent call last):
edgebot_1  |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
edgebot_1  |     await coroutine
edgebot_1  |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
edgebot_1  |     return await self.callback(update, context)
edgebot_1  |   File "/edgebot/edge.py", line 70, in message
edgebot_1  |     await query.run()
edgebot_1  |   File "/edgebot/utils.py", line 189, in run
edgebot_1  |     self._response = await CONV[cid(self.update)].ask(self.text)
edgebot_1  |   File "/usr/local/lib/python3.10/site-packages/EdgeGPT.py", line 241, in ask
edgebot_1  |     async for final, response in self.chat_hub.ask_stream(prompt=prompt):
edgebot_1  |   File "/usr/local/lib/python3.10/site-packages/EdgeGPT.py", line 208, in ask_stream
edgebot_1  |     yield False, response["arguments"][0]["messages"][0][
edgebot_1  | KeyError: 'messages'

**Comment by hdcola** [comment]
https://github.com/acheong08/EdgeGPT/pull/124
