### ISSUE TITLE
I got a error message

### ISSUE THREAD

**Issue by hdcola** [scmanjarrez/Edge-GPT-Telegram-Bot#3]
2023-03-02 11:24:53,294 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/hddev/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/opt/homebrew/Caskroom/miniconda/base/envs/hddev/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/Users/hd/work/Edge-GPT-Telegram-Bot/edge.py", line 39, in message
    await query.run()
  File "/Users/hd/work/Edge-GPT-Telegram-Bot/utils.py", line 163, in run
    await self.parse_message(message)
  File "/Users/hd/work/Edge-GPT-Telegram-Bot/utils.py", line 205, in parse_message
    text = REF.sub(
  File "/Users/hd/work/Edge-GPT-Telegram-Bot/utils.py", line 206, in <lambda>
    lambda x: (f"<a href='{references[x.group(1)]}'>"
KeyError: '1'

**Comment by scmanjarrez** [comment]
I'd need more information in order to debug it... I need at least the output of [text](https://github.com/scmanjarrez/Edge-GPT-Telegram-Bot/blob/master/utils.py#LL200C9-L200C54)
I'll add a condition to avoid the cases where some references are missing, but can't guaranteed if that'll fix the issue.

**Comment by hdcola** [comment]
> I'd need more information in order to debug it... I need at least the output of text
> I'll add a condition to avoid the cases where some references are missing, but can't guaranteed if that'll fix the issue.

I think it may be we have to a try catch log the error. 
Because when I try to use same question,  but I can't replay the error.

**Comment by scmanjarrez** [comment]
Check the new commit, it should fix that error. Sometime, the response from the api is "incomplete" (not all references in `text` present in `sourceAttributions`) and viceversa (not all references in `sourceAttributions` appearing on `text`). Now all references are shown in a new paragraph and the references present in `text` will be a link if they appear on `sourceAttributions`, otherwise are shown as plain text `[#]`

**Comment by hdcola** [comment]
Yes!
I have a suggestion for maybe have different log level record different message and we can configure for config file.

**Comment by scmanjarrez** [comment]
Yes, I agree, I should filter the logs i.e. apscheduler (typing), etc. Do you mind opening a new issue with the suggestion and configuration we should use? That way we can track it.
